# Generated by Django 3.0.7 on 2020-06-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='theDead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('maiden_name', models.CharField(max_length=255, verbose_name='Maiden Name')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('birth_date', models.DateField(blank=True, verbose_name='Birth Date')),
                ('death_date', models.DateField(blank=True, verbose_name='Death Date')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='Description')),
                ('website', models.URLField(blank=True, help_text='Add website describing or providing access to the collection.', max_length=255, verbose_name='Website')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_saved', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'The Dead',
                'verbose_name_plural': 'The Dead',
                'ordering': ['last_name'],
            },
        ),
    ]
