# Generated by Django 3.0.7 on 2020-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_dead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thedead',
            name='website',
            field=models.URLField(blank=True, help_text='Add website describing or providing more information about the collection.', max_length=255, verbose_name='Website'),
        ),
    ]
