# Generated by Django 3.0.7 on 2020-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_dead', '0005_thedead_grave_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thedead',
            name='grave_location',
            field=models.CharField(default='', max_length=255, verbose_name='Grave Coordinate'),
        ),
    ]
