# Generated by Django 3.0.7 on 2020-06-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_dead', '0007_auto_20200608_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='thedead',
            name='monument',
            field=models.BooleanField(default=True, verbose_name='Monument?'),
            preserve_default=False,
        ),
    ]
