# Generated by Django 3.0.7 on 2020-06-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_dead', '0008_thedead_monument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thedead',
            name='monument',
            field=models.BooleanField(help_text='Does the grave include a monument or tombstone?', verbose_name='Monument?'),
        ),
    ]
